# Site settings
title: 
subtitle: SELC PROJECT WEBSITE
email: curtisk808@gmail.com
description: 
baseurl: /selc_proejct # the subpath of your site, e.g. /blog
#exclude: []
url: "" # the base hostname & protocol for your site
author: curtis gibeom kim
#street_address: 123123
#city: 123123
#state: 
#zip_code: 
#country: 
#phone: 

# Social settings
500px_url:
facebook_url: 
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
#markdown: kramdown
#markdown: redcarpet
